### PR TITLE
Add template information to README

### PR DESCRIPTION
**Pull request by underscoreHao**
[3239 - Add template information to README]

#### 📲 What

Documentation for the installation and usage of templates

#### 🤔 Why

People re-writing the CLI or just using the templates themselves have to know how to use our templates.

#### 👀 Evidence

Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR

#### 🕵️ How to test

Notes for QA

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
The first two are the same is that right?

**Comment by underscoreHao** [comment]
> The first two are the same is that right?

If you mean the first two templates, then no. They are not the same. The `app` template contains absolutely everything, all projects, builds and infrastructure. The `api` template is just the CQRS WebAPI that can publish events to Service Bus.

**Comment by ElvenSpellmaker** [comment]
> > The first two are the same is that right?
> 
> If you mean the first two templates, then no. They are not the same. The `app` template contains absolutely everything, all projects, builds and infrastructure. The `api` template is just the CQRS WebAPI that can publish events to Service Bus.

Do they deliberately have the same name?

**Comment by underscoreHao** [comment]
> > > The first two are the same is that right?
> > 
> > 
> > If you mean the first two templates, then no. They are not the same. The `app` template contains absolutely everything, all projects, builds and infrastructure. The `api` template is just the CQRS WebAPI that can publish events to Service Bus.
> 
> Do they deliberately have the same name?

They don't have the same name? What is listed are the short names  `stacks-app-cqrs-events`, the other is `stacks-api-cqrs-events`. These are the names used by the `dotnet` command. The actual names of the templates are different.
- Amido Stacks CQRS Events
- Amido Stacks CQRS Events WebAPI

**Comment by ElvenSpellmaker** [comment]
Ahh OK XD

**Review by kleber-amido — APPROVED** [review]

**Pull request merged**
