### PR TITLE
Snyk fix CVE 2018 8292

### PR DESCRIPTION
**Pull request by dougbw**
[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]

#### 📲 What

Update the `xxAMIDOxx.xxSTACKSxx.Listener.UnitTests` project to use the latest version of `Amido.Stacks.Messaging.Azure.EventHub`

#### 🤔 Why

To resolve vulnerabilities identified by Snyk

#### 🛠 How

More in-depth discussion of the change or implementation.

#### 👀 Evidence

Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR

#### 🕵️ How to test

Notes for QA

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

### CODE REVIEW

**Comment by russellseymour** [comment]
Looks good :+1:

**Comment by russellseymour** [comment]
Approved

**Comment by scottvaughanamido** [comment]
This package should not have the "0.2.7-preview-master" version. This should be the full version.

**Pull request merged**
